import type { Project } from "./hooks/useSliderProjects";

export const projectData: Project[] = [
  {
    name: "Distripharmacias del Llano",
    description:
      "Ecommerce enfocado a ventas, ordenes, pagos y gestion de inventario de medicamentos",
    technologies: [
      "Angular",
      "Javascript",
      "Bootstrap",
      "Mongo DB",
      "Socket.io",
      "Jquery",
    ],
    slides: [
      { type: "image", src: "/projects/distripharmacias-del-llano/img1.png" },
      { type: "image", src: "/projects/distripharmacias-del-llano/img2.png" },
      {
        type: "video",
        src: "/projects/distripharmacias-del-llano/Ecommerce project.mp4",
        thumb: "/projects/distripharmacias-del-llano/img1.png",
      },
    ],
    image: "/projects/distripharmacias-del-llano/img1.png",
  },
  {
    name: "TodoServy",
    description:
      "¿Todos los servicios, profesionales y empresas cerca de mí? TodoServy es el directorio verificado más grande y confiable.",
    technologies: [
      "HTML",
      "CSS",
      "Javascript",
      "Laravel",
      "Bootstrap",
      "PHP",
      "MySQL",
    ],
    slides: [
      { type: "image", src: "/projects/todoservy/img2.png" },
      { type: "image", src: "/projects/todoservy/img1.png" },
      { type: "image", src: "/projects/todoservy/img3.png" },
      { type: "image", src: "/projects/todoservy/img4.png" },
      { type: "image", src: "/projects/todoservy/img5.png" },
      { type: "image", src: "/projects/todoservy/img6.png" },
      { type: "image", src: "/projects/todoservy/img7.png" },
      { type: "image", src: "/projects/todoservy/img8.png" },
      { type: "image", src: "/projects/todoservy/img9.png" },
      { type: "image", src: "/projects/todoservy/img10.png", isContain: true },
      { type: "image", src: "/projects/todoservy/img11.png", isContain: true },
    ],
    image: "/projects/todoservy/img2.png",
    link: "https://todoservy.com.co/",
  },
  {
    name: "TodoDomi",
    description:
      "Conoce a Todo Domi, la primera app delivery de la historia de Galápagos, diseñada para mayor comodidad de turistas extranjeros, nacionales y comunidad local.",
    technologies: ["React js", "Javascript", "SASS", "Bootstrap", "Rubi"],
    slides: [
      { type: "image", src: "/projects/tododomi/img1.png" },
      { type: "image", src: "/projects/tododomi/img2.png" },
      { type: "image", src: "/projects/tododomi/img3.png" },
      { type: "image", src: "/projects/tododomi/img4.png" },
      { type: "image", src: "/projects/tododomi/img5.png" },
      { type: "image", src: "/projects/tododomi/img6.png" },
      { type: "image", src: "/projects/tododomi/img7.png" },
      { type: "image", src: "/projects/tododomi/img8.png" },
      { type: "image", src: "/projects/tododomi/img9.png", isContain: true },
      { type: "image", src: "/projects/tododomi/img10.png", isContain: true },
      { type: "image", src: "/projects/tododomi/img11.png", isContain: true },
      { type: "image", src: "/projects/tododomi/img12.png", isContain: true },
      { type: "image", src: "/projects/tododomi/img13.png", isContain: true },
    ],
    image: "/projects/tododomi/img1.png",
    link: "https://customer.tododomi.com/",
  },
  {
    name: "Shepwashi",
    description:
      "Soluciones digitales para empresas. Personaliza la experiencia del cliente, reduce costos y crece tu negocio con herramientas para fidelizar clientes y optimizar procesos.",
    technologies: [
      "Next Js",
      "Javascript",
      "Tailwind CSS",
      "SASS",
      "Gsap",
      "Framer Motion",
    ],
    slides: [
      { type: "image", src: "/projects/shepwashi/img1.png" },
      { type: "image", src: "/projects/shepwashi/img2.png" },
      { type: "image", src: "/projects/shepwashi/img3.png" },
      { type: "image", src: "/projects/shepwashi/img4.png" },
      { type: "image", src: "/projects/shepwashi/img5.png" },
      { type: "image", src: "/projects/shepwashi/img6.png" },
      { type: "image", src: "/projects/shepwashi/img7.png" },
      { type: "image", src: "/projects/shepwashi/img8.png", isContain: true },
      { type: "image", src: "/projects/shepwashi/img9.png", isContain: true },
      { type: "image", src: "/projects/shepwashi/img10.png", isContain: true },
      { type: "image", src: "/projects/shepwashi/img11.png", isContain: true },
      { type: "image", src: "/projects/shepwashi/img12.png", isContain: true },
      { type: "image", src: "/projects/shepwashi/img13.png", isContain: true },
    ],
    image: "/projects/shepwashi/img1.png",
    link: "https://www.shepwashi.com/",
  },
  {
    name: "Shepwashi Dashboard",
    description:
      "Dashboard para gestionar proyectos, empleados, comisiones, gastos, tipos de contrato y rentabilidad",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "Recharts",
      "Swiper js",
      "Zustand",
      "Axios",
      "Tanstack Query",
      "Nest js",
      "Prisma",
      "PostgreSQL",
    ],
    slides: [
      { type: "image", src: "/projects/shepwashi-dashboard/img1.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img2.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img3.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img4.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img5.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img6.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img8.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img9.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img10.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img11.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img12.png" },
      { type: "image", src: "/projects/shepwashi-dashboard/img13.png" },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img14.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img15.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img16.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img17.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img18.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img19.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img20.png",
        isContain: true,
      },
    ],
    image: "/projects/shepwashi-dashboard/img13.png",
  },
  {
    name: "Ecuasuiza Ventas",
    description:
      "¿Buscas proteger tu vida y la de los tuyos? En Ecuasuiza te brindamos un servicio de seguros contra todo riesgo, ¡cuidamos tus bienes mas preciados!",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Recharts",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/ecuasuiza-ventas/img1.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img2.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img3.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img4.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img5.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img6.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img7.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img8.png" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img9.png" },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img10.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img11.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img12.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img13.png",
        isContain: true,
      },
    ],
    image: "/projects/ecuasuiza-ventas/img1.png",
  },
  {
    name: "Ecuasuiza Agentes",
    description:
      "Modulo administrativo para gestionar usuarios, coorporaciones, compañias, campañas, productos, planes y ordenes",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Dnd kit",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/ecuasuiza-agentes/img1.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img2.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img3.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img4.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img5.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img6.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img7.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img8.png" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img9.png" },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img10.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img11.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img12.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img13.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img14.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img15.png",
        isContain: true,
      },
    ],
    image: "/projects/ecuasuiza-agentes/img1.png",
  },
  {
    name: "Banco Bolivariano",
    description:
      "Dashboard para gestionar polizas, usuarios, oficinas, clientes mediante formularios, estadisticas y modulos informativos para tener un mejor control de las ventas",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "Recharts",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/banco-bolivariano/img1.png" },
      { type: "image", src: "/projects/banco-bolivariano/img2.png" },
      { type: "image", src: "/projects/banco-bolivariano/img3.png" },
      { type: "image", src: "/projects/banco-bolivariano/img4.png" },
      { type: "image", src: "/projects/banco-bolivariano/img5.jpg" },
      { type: "image", src: "/projects/banco-bolivariano/img6.png" },
      { type: "image", src: "/projects/banco-bolivariano/img7.png" },
      { type: "image", src: "/projects/banco-bolivariano/img8.png" },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img9.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img10.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img11.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img12.png",
        isContain: true,
      },
    ],
    image: "/projects/banco-bolivariano/img2.png",
  },
  {
    name: "Eranpay",
    description:
      "Dashboard multifuncional para gestion de transacciones, tarjetas, empresas, ecommerce, ordenes y soporte, la aplicación tiene un modulo para tema y otro para idioma",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "i18next",
      "Zustand",
      "Axios",
      "Tanstack Query",
      "Lightgallery",
      "Swiper js",
      "Mapbox",
      "Socket.io",
      "Rust",
    ],
    slides: [
      { type: "image", src: "/projects/eranpay/img1.png" },
      { type: "image", src: "/projects/eranpay/img2.png" },
      { type: "image", src: "/projects/eranpay/img3.png" },
      { type: "image", src: "/projects/eranpay/img16.png" },
      { type: "image", src: "/projects/eranpay/img4.png" },
      { type: "image", src: "/projects/eranpay/img5.png" },
      { type: "image", src: "/projects/eranpay/img6.png" },
      { type: "image", src: "/projects/eranpay/img7.png" },
      { type: "image", src: "/projects/eranpay/img8.png" },
      { type: "image", src: "/projects/eranpay/img9.png" },
      { type: "image", src: "/projects/eranpay/img10.png" },
      { type: "image", src: "/projects/eranpay/img11.png" },
      { type: "image", src: "/projects/eranpay/img12.png" },
      { type: "image", src: "/projects/eranpay/img13.png" },
      { type: "image", src: "/projects/eranpay/img14.png" },
      { type: "image", src: "/projects/eranpay/img15.png" },
      { type: "image", src: "/projects/eranpay/img18.png" },
      { type: "image", src: "/projects/eranpay/img19.png" },
      { type: "image", src: "/projects/eranpay/img20.png" },
      {
        type: "image",
        src: "/projects/eranpay/img21.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img22.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img23.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img24.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img25.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img26.png",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img27.png",
        isContain: true,
      },
    ],
    image: "/projects/eranpay/img1.png",
    link: "https://stgdashboard.eranpay.com/login",
  },
];
