import type { Project } from "./hooks/useSliderProjects";

export const projectData: Project[] = [
  {
    name: "Eranpay",
    description:
      "Dashboard multifuncional para gestion de transacciones, tarjetas, empresas, ecommerce, ordenes y soporte, la aplicación tiene un modulo para tema y otro para idioma",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "i18next",
      "Zustand",
      "Axios",
      "Tanstack Query",
      "Lightgallery",
      "Swiper js",
      "Mapbox",
      "Socket.io",
      "Rust",
    ],
    slides: [
      { type: "image", src: "/projects/eranpay/img1.webp" },
      { type: "image", src: "/projects/eranpay/img2.webp" },
      { type: "image", src: "/projects/eranpay/img3.webp" },
      { type: "image", src: "/projects/eranpay/img16.webp" },
      { type: "image", src: "/projects/eranpay/img4.webp" },
      { type: "image", src: "/projects/eranpay/img5.webp" },
      { type: "image", src: "/projects/eranpay/img6.webp" },
      { type: "image", src: "/projects/eranpay/img7.webp" },
      { type: "image", src: "/projects/eranpay/img8.webp" },
      { type: "image", src: "/projects/eranpay/img9.webp" },
      { type: "image", src: "/projects/eranpay/img10.webp" },
      { type: "image", src: "/projects/eranpay/img11.webp" },
      { type: "image", src: "/projects/eranpay/img12.webp" },
      { type: "image", src: "/projects/eranpay/img13.webp" },
      { type: "image", src: "/projects/eranpay/img14.webp" },
      { type: "image", src: "/projects/eranpay/img15.webp" },
      { type: "image", src: "/projects/eranpay/img18.webp" },
      { type: "image", src: "/projects/eranpay/img19.webp" },
      { type: "image", src: "/projects/eranpay/img20.webp" },
      {
        type: "image",
        src: "/projects/eranpay/img21.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img22.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img23.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img24.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img25.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img26.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/eranpay/img27.webp",
        isContain: true,
      },
    ],
    image: "/projects/eranpay/img1.webp",
    link: "https://devdash.eranpay.com",
  },
  {
    name: "Shepwashi",
    description:
      "Soluciones digitales para empresas. Personaliza la experiencia del cliente, reduce costos y crece tu negocio con herramientas para fidelizar clientes y optimizar procesos.",
    technologies: [
      "Next Js",
      "Javascript",
      "Tailwind CSS",
      "SASS",
      "Gsap",
      "Framer Motion",
    ],
    slides: [
      { type: "image", src: "/projects/shepwashi/img1.webp" },
      { type: "image", src: "/projects/shepwashi/img2.webp" },
      { type: "image", src: "/projects/shepwashi/img3.webp" },
      { type: "image", src: "/projects/shepwashi/img4.webp" },
      { type: "image", src: "/projects/shepwashi/img5.webp" },
      { type: "image", src: "/projects/shepwashi/img6.webp" },
      { type: "image", src: "/projects/shepwashi/img7.webp" },
      { type: "image", src: "/projects/shepwashi/img8.webp", isContain: true },
      { type: "image", src: "/projects/shepwashi/img9.webp", isContain: true },
      { type: "image", src: "/projects/shepwashi/img10.webp", isContain: true },
      { type: "image", src: "/projects/shepwashi/img11.webp", isContain: true },
      { type: "image", src: "/projects/shepwashi/img12.webp", isContain: true },
      { type: "image", src: "/projects/shepwashi/img13.webp", isContain: true },
    ],
    image: "/projects/shepwashi/img1.webp",
    /* link: "https://www.shepwashi.com/", */
  },
  {
    name: "Distripharmacias del Llano",
    description:
      "Ecommerce enfocado a ventas, ordenes, pagos y gestion de inventario de medicamentos",
    technologies: [
      "Angular",
      "Javascript",
      "Bootstrap",
      "Mongo DB",
      "Socket.io",
      "Jquery",
    ],
    slides: [
      { type: "image", src: "/projects/distripharmacias-del-llano/img1.webp" },
      { type: "image", src: "/projects/distripharmacias-del-llano/img2.webp" },
      {
        type: "video",
        src: "/projects/distripharmacias-del-llano/Ecommerce project.mp4",
        thumb: "/projects/distripharmacias-del-llano/img1.webp",
      },
    ],
    image: "/projects/distripharmacias-del-llano/img1.webp",
  },
  {
    name: "TodoServy",
    description:
      "¿Todos los servicios, profesionales y empresas cerca de mí? TodoServy es el directorio verificado más grande y confiable.",
    technologies: [
      "HTML",
      "CSS",
      "Javascript",
      "Laravel",
      "Bootstrap",
      "PHP",
      "MySQL",
    ],
    slides: [
      { type: "image", src: "/projects/todoservy/img2.webp" },
      { type: "image", src: "/projects/todoservy/img1.webp" },
      { type: "image", src: "/projects/todoservy/img3.webp" },
      { type: "image", src: "/projects/todoservy/img4.webp" },
      { type: "image", src: "/projects/todoservy/img5.webp" },
      { type: "image", src: "/projects/todoservy/img6.webp" },
      { type: "image", src: "/projects/todoservy/img7.webp" },
      { type: "image", src: "/projects/todoservy/img8.webp" },
      { type: "image", src: "/projects/todoservy/img9.webp" },
      { type: "image", src: "/projects/todoservy/img10.webp", isContain: true },
      { type: "image", src: "/projects/todoservy/img11.webp", isContain: true },
    ],
    image: "/projects/todoservy/img2.webp",
    link: "https://todoservy.com.co/",
  },
  {
    name: "TodoDomi",
    description:
      "Conoce a Todo Domi, la primera app delivery de la historia de Galápagos, diseñada para mayor comodidad de turistas extranjeros, nacionales y comunidad local.",
    technologies: ["React js", "Javascript", "SASS", "Bootstrap", "Rubi"],
    slides: [
      { type: "image", src: "/projects/tododomi/img1.webp" },
      { type: "image", src: "/projects/tododomi/img2.webp" },
      { type: "image", src: "/projects/tododomi/img3.webp" },
      { type: "image", src: "/projects/tododomi/img4.webp" },
      { type: "image", src: "/projects/tododomi/img5.webp" },
      { type: "image", src: "/projects/tododomi/img6.webp" },
      { type: "image", src: "/projects/tododomi/img7.webp" },
      { type: "image", src: "/projects/tododomi/img8.webp" },
      { type: "image", src: "/projects/tododomi/img9.webp", isContain: true },
      { type: "image", src: "/projects/tododomi/img10.webp", isContain: true },
      { type: "image", src: "/projects/tododomi/img11.webp", isContain: true },
      { type: "image", src: "/projects/tododomi/img12.webp", isContain: true },
      { type: "image", src: "/projects/tododomi/img13.webp", isContain: true },
    ],
    image: "/projects/tododomi/img1.webp",
    link: "https://customer.tododomi.com/",
  },
  {
    name: "Shepwashi Dashboard",
    description:
      "Dashboard para gestionar proyectos, empleados, comisiones, gastos, tipos de contrato y rentabilidad",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "Recharts",
      "Swiper js",
      "Zustand",
      "Axios",
      "Tanstack Query",
      "Nest js",
      "Prisma",
      "PostgreSQL",
    ],
    slides: [
      { type: "image", src: "/projects/shepwashi-dashboard/img1.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img2.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img3.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img4.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img5.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img6.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img8.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img9.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img10.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img11.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img12.webp" },
      { type: "image", src: "/projects/shepwashi-dashboard/img13.webp" },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img14.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img15.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img16.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img17.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img18.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img19.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/shepwashi-dashboard/img20.webp",
        isContain: true,
      },
    ],
    image: "/projects/shepwashi-dashboard/img13.webp",
  },
  {
    name: "Ecuasuiza Ventas",
    description:
      "¿Buscas proteger tu vida y la de los tuyos? En Ecuasuiza te brindamos un servicio de seguros contra todo riesgo, ¡cuidamos tus bienes mas preciados!",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Recharts",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/ecuasuiza-ventas/img1.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img2.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img3.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img4.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img5.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img6.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img7.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img8.webp" },
      { type: "image", src: "/projects/ecuasuiza-ventas/img9.webp" },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img10.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img11.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img12.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-ventas/img13.webp",
        isContain: true,
      },
    ],
    image: "/projects/ecuasuiza-ventas/img1.webp",
  },
  {
    name: "Ecuasuiza Agentes",
    description:
      "Modulo administrativo para gestionar usuarios, coorporaciones, compañias, campañas, productos, planes y ordenes",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Dnd kit",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/ecuasuiza-agentes/img1.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img2.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img3.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img4.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img5.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img6.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img7.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img8.webp" },
      { type: "image", src: "/projects/ecuasuiza-agentes/img9.webp" },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img10.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img11.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img12.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img13.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img14.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/ecuasuiza-agentes/img15.webp",
        isContain: true,
      },
    ],
    image: "/projects/ecuasuiza-agentes/img1.webp",
  },
  {
    name: "Banco Bolivariano",
    description:
      "Dashboard para gestionar polizas, usuarios, oficinas, clientes mediante formularios, estadisticas y modulos informativos para tener un mejor control de las ventas",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "Recharts",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/banco-bolivariano/img1.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img2.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img3.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img4.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img5.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img6.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img7.webp" },
      { type: "image", src: "/projects/banco-bolivariano/img8.webp" },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img9.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img10.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img11.webp",
        isContain: true,
      },
      {
        type: "image",
        src: "/projects/banco-bolivariano/img12.webp",
        isContain: true,
      },
    ],
    image: "/projects/banco-bolivariano/img2.webp",
  },
  {
    name: "Labreicis",
    description:
      "Dashboard para gestionar fases, parámetros, insumos, tareas, bodegas, ventas y reportes para el proceso de producción de camarones",
    technologies: [
      "React",
      "Vite",
      "Typescript",
      "Tailwind CSS",
      "Hero UI",
      "Ant Design",
      "Framer Motion",
      "Apexcharts",
      "Zustand",
      "Axios",
      "Express",
      "PostgreSQL",
      "Sequelize",
    ],
    slides: [
      { type: "image", src: "/projects/labreicis/img1.webp" },
      { type: "image", src: "/projects/labreicis/img2.webp" },
      { type: "image", src: "/projects/labreicis/img3.webp" },
      { type: "image", src: "/projects/labreicis/img4.webp" },
      { type: "image", src: "/projects/labreicis/img5.webp" },
      { type: "image", src: "/projects/labreicis/img6.webp" },
    ],
    image: "/projects/labreicis/img1.webp",
    link: "https://app.labreicis.com/",
  },
];

